// AUTO-GENERATED by typescript-type-def

export default types;
export namespace types {
    export type EffectAction = {

        /**
         * The tag, or `ACT_NONE` for none.
         */
        "act_tag": string;

        /**
         * The damage attribute, or `ATT_NONE` for none.
         */
        "attribute_tag": string;

        /**
         * Minimum parameters for this effect.
         */
        "min": [(string | null), (string | null)];

        /**
         * Maximum parameters for this effect.
         */
        "max": [(string | null), (string | null)];
    };
    export type ItemEffect = {
        "name": string;
        "tag": string;

        /**
         * Hit sound effect
         */
        "hit_se": (string | null);
        "group_tag": string;
        "actions": [types.EffectAction, types.EffectAction];
    };
}
