// AUTO-GENERATED by typescript-type-def

export default types;
export namespace types {
    export type Usize = number;
    export type I32 = number;
    export type Item = {
        "name": string;
        "tag": string;
        "image_no": types.Usize;
        "cost": types.I32;
        "use_type": string;
        "base": string;
        "level": types.Usize;
        "shape_type": string;
        "base_size": types.Usize;
        "quality_name": string;
        "size_name": string;
        "color": string;
        "categories": (string)[];
        "reasonable": (types.Usize)[];
        "strengthening": (types.Usize | null);
        "hp": (types.Usize | null);
        "mp": (types.Usize | null);
        "lp": (types.Usize | null);
        "atk": (types.Usize | null);
        "def": (types.Usize | null);
        "spd": (types.Usize | null);
        "damage_min": (types.Usize | null);
        "damage_max": (types.Usize | null);
        "doll_tendency_cute": (types.I32 | null);
        "doll_tendency_wise": (types.I32 | null);
        "doll_tendency_brave": (types.I32 | null);
        "doll_tendency_fool": (types.I32 | null);

        /**
         * Player character, relates to which player cannot use this item.
         */
        "player_characters": (types.Usize)[];
    };
}
