// AUTO-GENERATED by typescript-type-def

export default types;
export namespace types {
    export type I32 = number;
    export type U32 = number;
    export type F32 = number;
    export type Item = {

        /**
         * The item tag. This is the closest we get to a string id but it does not exist for all items.
         */
        "tag": (string | null);
        "library_note": (string | null);
        "name": (string | null);
        "temp_name": (string | null);
        "temp_end_event": (string | null);
        "sort": types.I32;
        "img_no": types.I32;
        "price": types.U32;
        "lv": types.U32;
        "element": (types.U32 | null);
        "element_value": (types.U32 | null);
        "elem_fire": boolean;
        "elem_ice": boolean;
        "elem_thunder": boolean;
        "elem_air": boolean;
        "pc": (types.I32)[];
        "hp": (types.I32 | null);
        "atk": (types.I32 | null);
        "def": (types.I32 | null);
        "spd": (types.I32 | null);
        "w_hp": (types.F32 | null);
        "w_mp": (types.F32 | null);
        "w_atk": (types.F32 | null);
        "w_def": (types.F32 | null);
        "w_spd": (types.F32 | null);

        /**
         * The DLC required for this item.
         */
        "dlc": (string | null);
        "use_tag": string;
        "kind_tag": string;
        "bme": (string | null);
        "bmee": (string | null);
        "cat": (string)[];
    };
}
