// AUTO-GENERATED by typescript-type-def

export default types;
export namespace types {
    export type U32 = number;
    export type PuniFeedingEventCondition = (({

        /**
         * A specific puni species.
         */
        "type": "PuniSpecies";
    } & {
        "species": string;
    }) | ({

        /**
         * A range for the energy value.
         */
        "type": "Energy";
    } & {
        "min": types.U32;
        "max": types.U32;
    }) | ({

        /**
         * A range for the color value.
         */
        "type": "Color";
    } & {
        "min": types.U32;
        "max": types.U32;
    }) | ({

        /**
         * A range for the mood value.
         */
        "type": "Mood";
    } & {
        "min": types.U32;
        "max": types.U32;
    }));

    /**
     * A feeding event where a unique item is awarded.
     */
    export type PuniFeedingUniqueEvent = {

        /**
         * The item tag
         */
        "item_tag": string;

        /**
         * The condition required to trigger this event.
         */
        "condition": types.PuniFeedingEventCondition;
    };
    export type Usize = number;

    /**
     * A puni species that can result from feeding the puni.
     */
    export type PuniFeedingSpecies = {

        /**
         * The name of this species
         */
        "name": string;
        "character_tag": string;
        "image_no": types.Usize;

        /**
         * The energy range for this species. This is localized as "Health" in the English translation of the game.
         */
        "energy": [types.U32, types.U32];

        /**
         * The color range for this species. This is localized as "Luster" in the English translation of the game.
         */
        "color": [types.U32, types.U32];

        /**
         * The mood range for this species.
         */
        "mood": [types.U32, types.U32];
        "rank_e": ([types.U32, types.U32] | null);
        "rank_d": ([types.U32, types.U32] | null);
        "rank_c": ([types.U32, types.U32] | null);
        "rank_b": ([types.U32, types.U32] | null);
        "rank_a": ([types.U32, types.U32] | null);
        "rank_s": ([types.U32, types.U32] | null);
        "categories": (string)[];
    };
    export type PuniFeedingData = {
        "unique_events": (types.PuniFeedingUniqueEvent)[];
        "species": (types.PuniFeedingSpecies)[];
    };
}
